### ISSUE TITLE
List in spanish

### ISSUE THREAD

**Issue by diegoalexander91** [Zimbra-Community/sa-alert-zimlet#3]
Hello
My mail server receives a lot of spam, but in Spanish.
Some matters are:

1- Header: Ultima advertencia

2- Header: LOAN OFFER

What additional information is required?
Does it work with my own SpamAssasin?

**Comment by diegoalexander91** [comment]
This is a recent message:

Return-Path: cbu11kuu@webmail.cbu.ca
X-DSPAM-Class: Innocent
X-DSPAM-Confidence: 0.61
X-DSPAM-Probability: 0.0000
X-Spam-Flag: NO
X-Spam-Score: -4.323
X-Spam-Level:
X-Spam-Status: No, score=-4.323 tagged_above=-10 required=8
	tests=[BAYES_00=-1.9, HTML_MESSAGE=0.001, RCVD_IN_DNSWL_NONE=-0.0001,
	RP_MATCHES_RCVD=-1.424, DSPAM.Innocent=-1.000]
	autolearn=unavailable autolearn_force=no
X-DSPAM-Result: Innocent
Received: from CBUSEG1.CBU.CA (cbuseg1.cbu.ca [142.12.73.56])
	by zmta.uniminuto.edu (Postfix) with ESMTPS id 40FE8C5F2E;
	Thu,  9 Jun 2016 13:50:29 -0500 (COT)
Received: from webmail.cbu.ca (Not Verified[142.12.73.39]) by CBUSEG1.CBU.CA with Trustwave SEG (v7,5,1,8064)
	id <B5759b39f0006>; Thu, 09 Jun 2016 15:21:19 -0300
Received: from CBUWEBMAIL [142.12.73.39] by webmail.cbu.ca with ESMTP
  (SMTPD-12.4.2.27) id cf6f0002bd846e26; Thu, 9 Jun 2016 15:21:18 -0300
From: "UNIMINUTO" <cbu11kuu@webmail.cbu.ca>
To: all@uniminuto.edu
Date: Thu, 09 Jun 2016 15:21:18 -0300
Subject: Muy importante
Mime-Version: 1.0
Content-Type: multipart/alternative;
  boundary="=_boundary0001_1.08D39079B48ACF6F"
Message-Id: <201606091521568.SM179588@CBUWEBMAIL>


The URL_PISH attribute does not appear

Help?

**Comment by barrydegraaff** [comment]
Yeah, I think you need to train your spam assassin a bit more... people need to `mark-as-spam` and in case you run 8.6, make sure to install all patches as zmtrainsa script was broken in some 8.6 versions.
